@baseUrl = http://localhost:9008

### Liveness Probe (Self)
GET {{baseUrl}}/health/live
Accept: application/json

### Readiness Probe (Dependencies)
GET {{baseUrl}}/health/ready
Accept: application/json
